# Copyright (c) 2016 Oracle and/or its affiliates. All rights reserved.
#
# Example of using Docker Compose to deploy a WebLogic Cluster from image '1221-domain'
# 
# This Docker Compose file will only work with Docker 1.10+ and Compose 1.6+
#
# To run, call:
#   $ docker-compose up
#
# To scale Managed Servers, open a new terminal and call:
#   $ docker-compose scale managedserver=2
#
# To scale Node Managers only instead, call:
#   $ docker-compose scale nodemanager=2
#
# Author: Bruno Borges <bruno.borges@oracle.com> 
#
# Note: If scaling dozens of instances of managed server at once, you may face a StuckThreadMaxTime
#
# Important: Restarting services will not work as expected due to hostnames not being properly setup by Docker Compose.
#            WLS still relying on IP addresses because of that.
#            See https://github.com/docker/compose/issues/2551#issuecomment-183082781
#            Issue is fixed on upstream only (1.7+), not 1.6.0
#            See https://github.com/docker/compose/pull/2853
#
version: '2'

services:

  wlsadmin:
    image: &image 1221-domain
    container_name: &admin wlsadmin
    networks:
      - wlsnet

  managedserver:
    image: *image
    command: createServer.sh
    networks:
      - wlsnet
    depends_on:
      - *admin

  nodemanager:
    image: *image
    command: createMachine.sh
    networks:
      - wlsnet
    depends_on:
      - *admin

networks:
  wlsnet:
    driver: bridge

